version: '3.7'
services:
    postgres:
        environment:
            # TODO: Use a more secure mechanism for managing secrets other than
            #       environment variables. I believe environment variables can
            #       unintentionally be leaked between containers.
            - "PGDATA=${PGDATA:-/var/lib/postgresql/data}"
            - "PGDATABASE=${POSTGRES_DB:-dev_chrisreyes_tasktracker}"
            - "PGPASSWORD=${C17_TASKTRACKER_POSTGRES_PASSWORD}"
            - "PGUSER=${C17_TASKTRACKER_POSTGRES_USER}"
            - "POSTGRES_DB=${POSTGRES_DB:-dev_chrisreyes_tasktracker}"
            - POSTGRES_INITDB_WALDIR
            - "POSTGRES_PASSWORD=${C17_TASKTRACKER_POSTGRES_PASSWORD}"
            - "POSTGRES_USER=${C17_TASKTRACKER_POSTGRES_USER}"
        healthcheck:
            test: pg_isready || exit 1
        image: 'postgres:11.2-alpine'
        networks:
            - task-net
        ports:
            - '5432:5432'
        volumes:
            - "./target/data:${PGDATA:-/var/lib/postgresql/data}"
            - "./resources/migrations/postgres:/docker-entrypoint-initdb.d"

networks:
    task-net:
        driver: bridge
