# Copyright (C) 2019  Christopher R. Reyes
#
# This file is part of Task Tracker.
#
# Task Tracker is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Task Tracker is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Task Tracker.  If not, see <https://www.gnu.org/licenses/>.

version: '3.7'
services:
    postgres:
        environment:
            # TODO: Use a more secure mechanism for managing secrets other than
            #       environment variables. I believe environment variables can
            #       unintentionally be leaked between containers.
            - "PGDATA=${PGDATA:-/var/lib/postgresql/data}"
            - "PGDATABASE=${POSTGRES_DB:-dev_chrisreyes_tasktracker}"
            - "PGPASSWORD=${C17_TASKTRACKER_POSTGRES_PASSWORD}"
            - "PGUSER=${C17_TASKTRACKER_POSTGRES_USER}"
            - "POSTGRES_DB=${POSTGRES_DB:-dev_chrisreyes_tasktracker}"
            - POSTGRES_INITDB_WALDIR
            - "POSTGRES_PASSWORD=${C17_TASKTRACKER_POSTGRES_PASSWORD}"
            - "POSTGRES_USER=${C17_TASKTRACKER_POSTGRES_USER}"
        healthcheck:
            test: pg_isready || exit 1
        image: 'postgres:11.2-alpine'
        networks:
            - task-net
        ports:
            - '5432:5432'
        volumes:
            - "./target/data:${PGDATA:-/var/lib/postgresql/data}"
            - "./resources/migrations/postgres:/docker-entrypoint-initdb.d"
    task-tracker:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - postgres
        environment:
            - C17_TASKTRACKER_POSTGRES_SECRET
            - AWS_PROFILE
        healthcheck:
            test: curl --fail http://localhost:5000/.internal/is_healthy || exit 1
        networks:
            - task-net
        ports:
            - "${C17_TASKTRACKER_BACKEND_PORT:-5000}:5000"

networks:
    task-net:
        driver: bridge
